[package]
name = "gpt-cli-app"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version="0.12.15", features=["json"]}
serde = {version="1.0.219",features=["derive"]}
serde_json = "1.0.140"
colored = "3.0.0"
dotenv = "0.15.0"
tokio= {version="1",features=["macros","full"]}
